// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWgFfk7fdEzDFMl_D7jhfKEnqAa-Gigso',
    appId: '1:1035452793612:web:d7ba2589b40af2c82dbf29',
    messagingSenderId: '1035452793612',
    projectId: 'test1-4abd3',
    authDomain: 'test1-4abd3.firebaseapp.com',
    storageBucket: 'test1-4abd3.appspot.com',
    measurementId: 'G-X98Z11MC9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuZwACFk5raByCKz04V0g0rpcIIUbgto4',
    appId: '1:1035452793612:android:f0fa0d4f288aa7a32dbf29',
    messagingSenderId: '1035452793612',
    projectId: 'test1-4abd3',
    storageBucket: 'test1-4abd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaBqZSmwAzPF6b_o2p2V63KlAhaDMmn54',
    appId: '1:1035452793612:ios:54157711a79a88412dbf29',
    messagingSenderId: '1035452793612',
    projectId: 'test1-4abd3',
    storageBucket: 'test1-4abd3.appspot.com',
    iosBundleId: 'com.example.lab42',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaBqZSmwAzPF6b_o2p2V63KlAhaDMmn54',
    appId: '1:1035452793612:ios:66f09029d11051192dbf29',
    messagingSenderId: '1035452793612',
    projectId: 'test1-4abd3',
    storageBucket: 'test1-4abd3.appspot.com',
    iosBundleId: 'com.example.lab42.RunnerTests',
  );
}
